kind: Secret
apiVersion: v1
metadata: 
  name: webapp-secret
  namespace: web-app
data:
  MONGODB_URI : bW9uZ29kYjovL2FkbWluOmFkbWluMTIzQG1vbmdvLXNlcnZpY2U6MjcwMTcvZHJpdmUtY2xvbmU/YXV0aFNvdXJjZT1hZG1pbgo=
  #mongodb://admin:admin123@mongo-service:27017/drive-clone?authSource=admin
  JWT_SECRET: MzM5Yzk0YzMyMjZiNjA2NjJkMThlZjM5NjEyZDllMGQK
  #339c94c3226b60662d18ef39612d9e0d
  
